#!/bin/bash
sudo apt update && sudo apt upgrade -y
sudo apt-get install git-all -y
sudo apt-get install curl -y
sudo su
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
git clone https://github.com/AleoHQ/leo
cd leo
cargo install --path .
cd ..
